Пример с кастомным  @@iterator для for...of
HowProgrammingWorks/Iteration pull request #15
Opened 2019-09-30 12:20 UTC by svetley1

Пример для объяснения, что 
1) for...of работает с сущностями у которых есть метод @@iterator, то есть с перечисляемыми
2) @@iterator можно задавать кастомный и он так же будет работать с for...of

2021-02-09 23:59 UTC, DzyubSpirit requested changes
Please run `npx eslint --fix JavaScript/6-for-of.js` to fix and check your codestyle

2021-02-09 23:59 UTC, DzyubSpirit commented on JavaScript/6-for-of.js
> +        index = 0;
You don't need your index to be undefined if you immediatly set it to zero after the check.
Just assign zero to index in the declaration above and check for equality to 0 here. Comparing with zero is more natural than to undefined

2021-02-09 23:59 UTC, DzyubSpirit commented on JavaScript/6-for-of.js
> +      if (index === this.length - 1 || index === this.length - 2) {
If the step value changes by any reason (PM comes and says that users hate even indicies and want them to be divisible by Seven), this condition would have to be refactored as well.
Could you remake this condition so it would be adaptable to step constant changes? If you find a way it will also allow you to remove the above `if (index === 0) { ... }` clause without errors in the logic

2021-02-16 21:04 UTC, DzyubSpirit requested changes
Good stuff but, please, run ```npx eslint --fix JavaScript/6-for-of.js``` before each time you're sending code for the review

2021-02-17 15:56 UTC, svetley1 commented
> Good stuff but, please, run `npx eslint --fix JavaScript/6-for-of.js` before each time you're sending code for the review

Этот кейс решается посредством gh-actions ( https://github.com/actions/setup-node ). У меня есть свои причины не скачивать репозиторий для локального редактирования с workflow. Как минимум, мне проще вносить мелкие изменения в онлайн редакторе, а не скачивать все 100500 репозиториев для этого. Но в любом случае, не думаю, что "next time" будет.

2021-02-18 09:02 UTC, DzyubSpirit commented
Сам был бы рад, если бы кто-либо уделил время, чтобы настроить CI. 
Я тоже не скачивал репозитории, а проверял с помощью [repl.it](https://repl.it).

Till no next time!

2021-02-18 09:06 UTC, merged